networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:    

services:

  # VERİ KATMANI
  postgres:
    image: postgres:16-alpine
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sentiric-infrastructure/postgres-init:/docker-entrypoint-initdb.d
    # ports:
    #   - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - data
    restart: always

  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    env_file:
      - ./.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    # ports:
    #   - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    #   - "15672:15672"
    networks:
      - sentiric-net
    profiles:
      - default
      - data
    restart: always   

  media-service:
    build:
      context: ../sentiric-media-service
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: sentiric-media-service
    env_file:
      - ./.env
    volumes:
      - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro
    ports:
      - "${RTP_SERVICE_PORT_MIN:-10000}-${RTP_SERVICE_PORT_MAX:-10100}:${RTP_SERVICE_PORT_MIN:-10000}-${RTP_SERVICE_PORT_MAX:-10100}/udp"
      # - "${MEDIA_SERVICE_GRPC_PORT}:${MEDIA_SERVICE_GRPC_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - telekom
    restart: always

  user-service:
    build:
      context: ../sentiric-user-service
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: sentiric-user-service
    env_file:
      - ./.env
    volumes:
      - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro
    # ports:
    #   - "${USER_SERVICE_GRPC_PORT}:${USER_SERVICE_GRPC_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - app
    restart: always    

  # UYGULAMA SERVİSLERİ
  agent-service: 

    build:
      context: .
      dockerfile: Dockerfile         
      args:
        SERVICE_NAME: sentiric-agent-service

    env_file: 
      - ./.env

    volumes:
      - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro

    # ports:
    #   - "${AGENT_SERVICE_GRPC_PORT}:${AGENT_SERVICE_GRPC_PORT}"

    networks:
      - sentiric-net
    
    profiles:
      - default
      - app

    restart: always