# docker-compose.service.yml dosyasının GÜNCEL içeriği
services:
  agent-service:
    image: ${DOCKR_REGISTRY:-ghcr.io/sentiric}/sentiric-agent-service:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiric_agent_service
    env_file:
      - ./.env
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - MEDIA_SERVICE_GRPC_URL=${MEDIA_SERVICE_GRPC_URL}
      - DATABASE_URL=${POSTGRES_URL} # <-- YENİ EKLENEN SATIR
    networks:
      - sentiric-net
    restart: always

networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}