services:
  agent-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-agent-service:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiric_agent_service
    # Bu servisin kendi .env dosyasını ve/veya ana .env dosyasını kullanmasını sağlar
    env_file:
      - ./.env
    networks:
      - sentiric-net
    restart: always
    # RabbitMQ servisi sağlıklı bir şekilde çalışmaya başlamadan bu servisi başlatma
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge